// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package io.firkin.schemaregistry.versioning.simple.protobuf.evolution;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string given_name = 2;</code>
     */
    boolean hasGivenName();
    /**
     * <code>optional string given_name = 2;</code>
     */
    java.lang.String getGivenName();
    /**
     * <code>optional string given_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getGivenNameBytes();

    /**
     * <code>optional string family_name = 3;</code>
     */
    boolean hasFamilyName();
    /**
     * <code>optional string family_name = 3;</code>
     */
    java.lang.String getFamilyName();
    /**
     * <code>optional string family_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getFamilyNameBytes();

    /**
     * <code>optional string date_of_birth = 4;</code>
     */
    boolean hasDateOfBirth();
    /**
     * <code>optional string date_of_birth = 4;</code>
     */
    java.lang.String getDateOfBirth();
    /**
     * <code>optional string date_of_birth = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateOfBirthBytes();

    /**
     * <code>optional string date_of_death = 5;</code>
     */
    boolean hasDateOfDeath();
    /**
     * <code>optional string date_of_death = 5;</code>
     */
    java.lang.String getDateOfDeath();
    /**
     * <code>optional string date_of_death = 5;</code>
     */
    com.google.protobuf.ByteString
        getDateOfDeathBytes();
  }
  /**
   * Protobuf type {@code io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      id_ = 0L;
      givenName_ = "";
      familyName_ = "";
      dateOfBirth_ = "";
      dateOfDeath_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              givenName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              familyName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dateOfBirth_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dateOfDeath_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.class, io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int GIVEN_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object givenName_;
    /**
     * <code>optional string given_name = 2;</code>
     */
    public boolean hasGivenName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string given_name = 2;</code>
     */
    public java.lang.String getGivenName() {
      java.lang.Object ref = givenName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          givenName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string given_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGivenNameBytes() {
      java.lang.Object ref = givenName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        givenName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAMILY_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object familyName_;
    /**
     * <code>optional string family_name = 3;</code>
     */
    public boolean hasFamilyName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string family_name = 3;</code>
     */
    public java.lang.String getFamilyName() {
      java.lang.Object ref = familyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          familyName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string family_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyNameBytes() {
      java.lang.Object ref = familyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        familyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_OF_BIRTH_FIELD_NUMBER = 4;
    private volatile java.lang.Object dateOfBirth_;
    /**
     * <code>optional string date_of_birth = 4;</code>
     */
    public boolean hasDateOfBirth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string date_of_birth = 4;</code>
     */
    public java.lang.String getDateOfBirth() {
      java.lang.Object ref = dateOfBirth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateOfBirth_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string date_of_birth = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateOfBirthBytes() {
      java.lang.Object ref = dateOfBirth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfBirth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_OF_DEATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object dateOfDeath_;
    /**
     * <code>optional string date_of_death = 5;</code>
     */
    public boolean hasDateOfDeath() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string date_of_death = 5;</code>
     */
    public java.lang.String getDateOfDeath() {
      java.lang.Object ref = dateOfDeath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateOfDeath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string date_of_death = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDateOfDeathBytes() {
      java.lang.Object ref = dateOfDeath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfDeath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, givenName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, familyName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dateOfBirth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dateOfDeath_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, givenName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, familyName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dateOfBirth_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dateOfDeath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person other = (io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasGivenName() == other.hasGivenName());
      if (hasGivenName()) {
        result = result && getGivenName()
            .equals(other.getGivenName());
      }
      result = result && (hasFamilyName() == other.hasFamilyName());
      if (hasFamilyName()) {
        result = result && getFamilyName()
            .equals(other.getFamilyName());
      }
      result = result && (hasDateOfBirth() == other.hasDateOfBirth());
      if (hasDateOfBirth()) {
        result = result && getDateOfBirth()
            .equals(other.getDateOfBirth());
      }
      result = result && (hasDateOfDeath() == other.hasDateOfDeath());
      if (hasDateOfDeath()) {
        result = result && getDateOfDeath()
            .equals(other.getDateOfDeath());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasGivenName()) {
        hash = (37 * hash) + GIVEN_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getGivenName().hashCode();
      }
      if (hasFamilyName()) {
        hash = (37 * hash) + FAMILY_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFamilyName().hashCode();
      }
      if (hasDateOfBirth()) {
        hash = (37 * hash) + DATE_OF_BIRTH_FIELD_NUMBER;
        hash = (53 * hash) + getDateOfBirth().hashCode();
      }
      if (hasDateOfDeath()) {
        hash = (37 * hash) + DATE_OF_DEATH_FIELD_NUMBER;
        hash = (53 * hash) + getDateOfDeath().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person)
        io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.class, io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.Builder.class);
      }

      // Construct using io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        givenName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        familyName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dateOfBirth_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dateOfDeath_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_descriptor;
      }

      public io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person getDefaultInstanceForType() {
        return io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.getDefaultInstance();
      }

      public io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person build() {
        io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person buildPartial() {
        io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person result = new io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.givenName_ = givenName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.familyName_ = familyName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dateOfBirth_ = dateOfBirth_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dateOfDeath_ = dateOfDeath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person) {
          return mergeFrom((io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person other) {
        if (other == io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasGivenName()) {
          bitField0_ |= 0x00000002;
          givenName_ = other.givenName_;
          onChanged();
        }
        if (other.hasFamilyName()) {
          bitField0_ |= 0x00000004;
          familyName_ = other.familyName_;
          onChanged();
        }
        if (other.hasDateOfBirth()) {
          bitField0_ |= 0x00000008;
          dateOfBirth_ = other.dateOfBirth_;
          onChanged();
        }
        if (other.hasDateOfDeath()) {
          bitField0_ |= 0x00000010;
          dateOfDeath_ = other.dateOfDeath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object givenName_ = "";
      /**
       * <code>optional string given_name = 2;</code>
       */
      public boolean hasGivenName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string given_name = 2;</code>
       */
      public java.lang.String getGivenName() {
        java.lang.Object ref = givenName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            givenName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string given_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGivenNameBytes() {
        java.lang.Object ref = givenName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          givenName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string given_name = 2;</code>
       */
      public Builder setGivenName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        givenName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string given_name = 2;</code>
       */
      public Builder clearGivenName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        givenName_ = getDefaultInstance().getGivenName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string given_name = 2;</code>
       */
      public Builder setGivenNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        givenName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object familyName_ = "";
      /**
       * <code>optional string family_name = 3;</code>
       */
      public boolean hasFamilyName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string family_name = 3;</code>
       */
      public java.lang.String getFamilyName() {
        java.lang.Object ref = familyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            familyName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string family_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFamilyNameBytes() {
        java.lang.Object ref = familyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          familyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string family_name = 3;</code>
       */
      public Builder setFamilyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        familyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string family_name = 3;</code>
       */
      public Builder clearFamilyName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        familyName_ = getDefaultInstance().getFamilyName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string family_name = 3;</code>
       */
      public Builder setFamilyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        familyName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateOfBirth_ = "";
      /**
       * <code>optional string date_of_birth = 4;</code>
       */
      public boolean hasDateOfBirth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string date_of_birth = 4;</code>
       */
      public java.lang.String getDateOfBirth() {
        java.lang.Object ref = dateOfBirth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateOfBirth_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string date_of_birth = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateOfBirthBytes() {
        java.lang.Object ref = dateOfBirth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateOfBirth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date_of_birth = 4;</code>
       */
      public Builder setDateOfBirth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dateOfBirth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date_of_birth = 4;</code>
       */
      public Builder clearDateOfBirth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dateOfBirth_ = getDefaultInstance().getDateOfBirth();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date_of_birth = 4;</code>
       */
      public Builder setDateOfBirthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dateOfBirth_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateOfDeath_ = "";
      /**
       * <code>optional string date_of_death = 5;</code>
       */
      public boolean hasDateOfDeath() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string date_of_death = 5;</code>
       */
      public java.lang.String getDateOfDeath() {
        java.lang.Object ref = dateOfDeath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dateOfDeath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string date_of_death = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDateOfDeathBytes() {
        java.lang.Object ref = dateOfDeath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateOfDeath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date_of_death = 5;</code>
       */
      public Builder setDateOfDeath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dateOfDeath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date_of_death = 5;</code>
       */
      public Builder clearDateOfDeath() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dateOfDeath_ = getDefaultInstance().getDateOfDeath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date_of_death = 5;</code>
       */
      public Builder setDateOfDeathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dateOfDeath_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person)
    }

    // @@protoc_insertion_point(class_scope:io.firkin.schemaregistry.versioning.simple.protobuf.evolution.Person)
    private static final io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person();
    }

    public static io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public io.firkin.schemaregistry.versioning.simple.protobuf.evolution.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022=io.firkin.schemaregistry" +
      ".versioning.simple.protobuf.evolution\"k\n" +
      "\006Person\022\n\n\002id\030\001 \001(\003\022\022\n\ngiven_name\030\002 \001(\t\022" +
      "\023\n\013family_name\030\003 \001(\t\022\025\n\rdate_of_birth\030\004 " +
      "\001(\t\022\025\n\rdate_of_death\030\005 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_firkin_schemaregistry_versioning_simple_protobuf_evolution_Person_descriptor,
        new java.lang.String[] { "Id", "GivenName", "FamilyName", "DateOfBirth", "DateOfDeath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
